---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCwaYqFP4Msf+CIytOBP7HfGKVBjVNrwilrpX2XVcyOsJkxGqOyvyAOwoR3DU64MNSS1Xa3ouOQQ+iqIW0Di/jnHjB3MwmFlIGm+iLozejt6a391CBLStKv+EPKpgxiVsiejtMMGOFOiD5XObFBTN5s/IqdBnObsUywGrwZCQ9TQskMmax87SzF9F5GSYDvMwJjTIVNMr2zSxnFoosxFIzcYHBJgzYrDnisHtqMkdIfBixnMlOxkbiQtI6DPrgf/T2GJpv/N75I0p1eW0JvjE2tsRkqSDCr4NhSCyrh1txRGAOZSTYt+31wZaJDRys9Pla1P407x0XHt/9W/t6cHjK0QksFWV17hVZLIN+HmIkC0FgAORkeAlwBMATQYGI1yLSF8mQ3Fipjli/CiEzJrssMQt1eH+fNjTWvoO0MU0UnzR7SJc0Dntl+0AmbHVXL3M/7sOb8A+fhn7+dM+fzxgLIFnSB0LX3IFzY0gFmOOd9jcDqQ3Gn0T8u6Ej4U88Mqc+nm0TULxaD74PLsCBgh3h4/5lILC55iCKR16yXTpGX4+jJQVrC5HrGRDQuYDdwCQsHeywrJpIBSrPEgOwbJuLTGLTcZmCJZWtOUWUrGU5i2yqkvXrit5NqWPadyIrseioFaSt8WVIJImNjt9rpmcJ8K8yq2CCXuyzafGviGzzm4xnYXXZE1RZMZmxK1osJV5PPmBqIc1N2CMkBUllnlx1YNbTgO9SjqQgYbJuLhtKlo8fp3sbqvxSXSjk5198CVMtr9tKOktfdVIMALvcKT/MFuHO/IX2nm3n2HWJm+5kGBIeGSkw1hg7YojKbjErXz6OI0Y5C3FNq8syH7Lv1Ul2ieXEDJNsGZ9qT0o78WKH5KVLEEYn4R1Bjxhm/q/ds0cZb5MEVt374r0H3cW/nCZ9/p+bbtoPRhb/AZKG8rGAI/RGMBIevydbg77twflCq
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
