---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAXpcPiPu4F1A+lImcxmozaC9N0DuQQuzVAqjTCsRFDOva0Dl+9Hwm9Nf9T0S+esiejOld+P3a6T+ANR9nvHHsCrNNfIwtArc8fu8U14VYqMJTdRf81Ln08xMzbbDTcFJ76EXvq13x/pSNNvxwvl4uxUH54VZElCtOg63YpdsaIvp7/A3mc3kBNYOx9z4MikwJHBBdeuOq8zuE2I77PzPpz38TE7lA9i3ZZ5n7//+U5o7bQ4xyJpSRjWAGIu5Slra4DWGXcBhQusLWyyZX4LPMncqoZXOdYnOoCw9okGuF1oxu+KowE+OvTT9H+zIxF2O5x8LJz4KFqzAnOhFRz9W3y6gHkAvy7YoiCsdw3og/KqBucPewl7i0gzja2QzLgF5UznNsxqmzpsXAqGBE/IBHA7aStm30FDws3LX3U3Vl7TarkG0Aae/gQAS12OwGK4Eov6Czq49J3aYHgBtIQAXuD4/chPCYK2+DTMPdVkS/HCDyteiKB2kaOFU9bScrBToE5su+OYN7dlyoV6FtAW9bhgCfa+kxDuRP0rF2QiQ73KHc1L3ng7CJ9NFM40Zf3o3BuRn3ZUtGQmVhbc92Z4PUUtC/JKBmbWlUVaf/c08qeaGGPdcaz/27vp+m1iLqoG17z4yzeV4cvLWEjzqpCWNasgAQ0/CSqjWShrykiI78KsDc/yMAXMHfnaqWxgwKtKi3Jg02rdMIOWO3Za6ilCEFvRD6YKrfd5TxKYPoPtgk3KAulHTXbwGZgaVXYsMpzIRFY382CN/chAzMyVWwEwXy/amsUicK9qePrrE+nfOYws2/1qpW0GbXnXhBNPBFAaXQxhmKMU7MgY0bdekRjiTca1ZqoaZJcV04c9qt93Dk7jZ3ln+E5KAP+q/7LUzJ0Zlu7bSpZM1SYIYotyoDttU3rzB8+Su6AZZtNUsL8u/ejMxZGQMnDqGM9rc1kcMwu
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
