apiVersion: v1
kind: Service
metadata:
  name: trust-service
  namespace: default
spec:
  selector:
    app: trust-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
