---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: trust-repo
  namespace: flux-system
spec:
  secretRef:
    name: regcred
  image: docker.io/narea/trust-service
  interval: 30s
