---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: trust-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: trust-repo
  policy:
    semver:
      range: '>=1.0.0'
