services:
  trust-service:
    image: narea/trust-service:1.0.224
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "9080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    pull_policy: always
